name: MY ARTIFACT DEPLOYMENT
on:
  workflow_dispatch:

jobs:
  normal_shell:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          echo 'hi this is a normal script message and this is second kjkjkjkjkjkjkjk djkdjkjdsd
          dsldsldlsd uieurieururuehfjhfjd fdfkdjkfdkjkd dfdhjhjd dfhdjfhjdhfjdhf dfjhdjfhjdhjfh'
