name: My First Workflow

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from my first job!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'this is the second job'
      - run: echo 'and second job is created by amar'
  third-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'this is third job'
  forth-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hi this is forth job'
  fifth-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'this is fifth job'