name: SAFE DEPLOYMENT WORKFLOW
on:
  workflow_dispatch:
jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: check if file exists fixed
        run: |
          echo 'Current Address Directory'
          pwd
          echo 'File in this workspace'
          ls -R
          echo 'Reading content of app.html'
          cat app.html
      - name: Checking HTML Quality
        run: |
          echo 'Scanning app.html'
          echo 'Quality check passed'
  quality-check2:
    runs-on: ubuntu-check
    steps:
      - name: check i code exists 2
        run: |
          echo 'finding app.html'
          cat app.html
  deploy-to-production:
    runs-on: ubuntu-latest
    needs: quality-check
    environment:
      name: production-deployment
      url: https://my-awesome-app.com
    steps:
      - name: Live Deployment
        run: |
          echo 'Deploying app.html to the live server'
          echo 'Deployment successful'    