name: SAFE DEPLOYMENT2 WORKFLOW
on:
  workflow_dispatch:
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: find app.html file 
        run: |
          echo 'finding app.html file'
          cat app.html
            