name: HTML QUALITY CHECK
on:
  workflow_dispatch:
jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: Cache HTML HintTool
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: html-lint-cache-v1
          restore-keys: |
            html-lint-cache-
      - name: install html hint
        run: npm install -g htmlhint
      - name: CHECK out html
        run: htmlhint app.html 