name: Production Deployment

on:
  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: echo "🚀 Production deployment done"